# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: Register AzureML Environment

variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: PRD environment
    - template: ../config/config-infra-prod.yml
- ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    # 'develop' or feature branches: DEV environment
    - template: ../config/config-infra-dev.yml

parameters:
- name: version
  type: string
  displayName: Submission Method
  default: aml-cli-v2
  values:
  - aml-cli-v2
  - aml-python-sdk
- name: experiment_name
  type: string
  default: hello_world_cli
- name: environment_file
  displayName: environment file
  type: string
  default: register_environment.yaml
- name: environment_name
  displayName: environment name
  type: string

trigger:
- none

pool:
  vmImage: ubuntu-20.04

steps:
- checkout: self
  path: s/

- template: ../templates/${{ parameters.version }}/install-aml.yml
- template: ../templates/${{ parameters.version }}/connect-to-workspace.yml
- template: ../templates/${{ parameters.version }}/register-environment.yml
  parameters:
    experiment_name: ${{ parameters.experiment_name }}
    environment_name: ${{ parameters.environment_name }}
    environment_file: ${{ parameters.environment_file }}


