$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: hello-world-environment
image: mcr.microsoft.com/azureml/minimal-ubuntu18.04-py37-cpu-inference:20220425.v2
conda_file: conda_requirements.yaml
description: Environment created from a Docker image plus Conda environment.