# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
- name: experiment_name
  type: string
- name: environment_name
  type: string
- name: environment_file
  type: string

steps:
  - task: AzureCLI@2
    displayName: Register environment
    continueOnError: true
    inputs:
      azureSubscription: $(ado_service_connection_rg) #needs to have access at the RG level
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az ml environment create -f src/${{ parameters.experiment_name }}/environment/${{ parameters.environment_file }} --name ${{ parameters.environment_name }}