parameters:
- name: experiment_name
  type: string
- name: environment_name
  type: string
- name: environment_file
  type: string

steps:
  - task: AzureCLI@2
    displayName: Register environment
    inputs:
      azureSubscription: $(ado_service_connection_aml_ws)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        python src/${{ parameters.experiment_name }}/environment/${{ parameters.environment_file }} --environment_name ${{ parameters.environment_name }} --conda_file_path src/${{ parameters.experiment_name }}/environment/conda_requirements.yaml